services:

  postgres:
    image: postgres:16-alpine
    container_name: securebank-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: securebank
      POSTGRES_USER: securebank
      POSTGRES_PASSWORD: securebankpass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U securebank -d securebank"]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    build: .
    container_name: securebank-app
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      NODE_ENV: development
      PORT: 3000
      SESSION_SECRET: ${SESSION_SECRET}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: securebank
      DB_USER: securebank
      DB_PASSWORD: securebankpass
      DATABASE_URL: postgresql://securebank:securebankpass@postgres:5432/securebank

    ports:
      - "3000:3000"


volumes:
  postgres_data: