services:
  postgres:
    image: postgres:16-alpine
    container_name: securebank-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: securebank
      POSTGRES_USER: securebank
      POSTGRES_PASSWORD: securebankpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U securebank -d securebank"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
